version: '3'

services:
  frontend:
    build: 
      context: ./frontend-client
      dockerfile: Dockerfile.dev
    restart: "unless-stopped"
    ports: 
      - "4001:3000"
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public
  backend:
    build:
      context: ./backend-server
      dockerfile: Dockerfile.dev
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev