apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers: 
    - name: client
      image: jonpham/fib-react-client
      ports: 
        - containerPort: 3000 # REACT-PORT